version: 2.1

orbs:
  node: artsy/node@1.0.0
  queue: eddiewebb/queue@1.0.110

commands:
  persist-manifests:
    steps:
      - store_artifacts:
          path: .gudetama-manifests
  run-if-needed:
    parameters:
      step:
        type: string
    steps:
      - run:
          name: |
            Run '<< parameters.step >>' if needed
          command: gudetama run-if-needed << parameters.step >>
          # command: |
          #   node -e 'require("child_process").execSync(require("./gudetama.config.js").steps["<< parameters.step >>"].command, {stdio: "inherit"})'

  setup:
    steps:
      - run:
          name: install gudetama
          command: |
            curl -s -L https://github.com/artsy/gudetama/releases/download/v1.0.0-14/install.sh | source /dev/stdin
      - add_ssh_keys:
          fingerprints:
            - 'ba:dc:36:72:d2:df:5e:68:cc:1e:4e:b8:39:a4:5a:d8'
      - checkout
      - run-if-needed:
          step: install-node-modules

jobs:
  test:
    executor: node/build
    steps:
      - setup
      - run-if-needed:
          step: type-check
      - run-if-needed:
          step: test
      - persist-manifests

  deploy:
    executor: node/build
    steps:
      - setup
      - queue/until_front_of_line:
          time: '2' # how long a queue will wait until the job exits
          only-on-branch: master # restrict queueing to a specific branch (default *)
          consider-job: false # block whole workflow if any job still running
      - run:
          name: release
          command: yarn release

workflows:
  test-deploy:
    jobs:
      - test
      - deploy:
          context: npm-deploy
          requires:
            - test
          filters:
            branches:
              only:
                - master
