version: 2.1

orbs:
  node: artsy/node@1.0.0
  queue: eddiewebb/queue@1.0.110

jobs:
  deploy:
    executor: node/build
    steps:
      - run:
          name: install gudetama
          command: |
            curl -s https://raw.githubusercontent.com/artsy/gudetama/8d54748eedce2f63279164266078dd0586419860/install.sh | source /dev/stdin
      - queue/until_front_of_line:
          time: "2" # how long a queue will wait until the job exits
          only-on-branch: master # restrict queueing to a specific branch (default *)
          consider-job: false # block whole workflow if any job still running
      - add_ssh_keys:
          fingerprints:
            - 'ba:dc:36:72:d2:df:5e:68:cc:1e:4e:b8:39:a4:5a:d8'
      - checkout
      - run:
          name: install node_modules
          command: gudetama run-if-needed install_node_modules
      - run:
          name: deploy
          command: ./scripts/deploy.sh

workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
