version: 2.1

orbs:
  yarn: artsy/yarn@4.0.2
  node: artsy/node@1.0.0

jobs:
  deploy:
    executor: node/build
    steps:
      - checkout
      - yarn install
      - run:
          name: deploy
          command: ./scripts/deploy

workflows:
  deploy:
    jobs:
      - yarn/workflow-queue:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - yarn/workflow-queue
          filters:
            branches:
              only:
                - master
