version: 2.1

orbs:
  yarn: artsy/yarn@4.0.2
  node: artsy/node@1.0.0

jobs:
  deploy:
    executor: node/build
    steps:
      - run:
          name: deploy
          command: ./scripts/deploy

workflows:
  deploy:
    jobs:
      - yarn/workflow-queue
      - yarn/update-cache:
          requires:
            - yarn/workflow-queue
      - deploy:
          requires:
            - yarn/update-cache
          filters:
            branches:
              only:
                - master
