version: 2.1

orbs:
  yarn: artsy/yarn@4.0.2

jobs:
  deploy:
    steps:
      - run:
          name: deploy
          command: ./scripts/deploy

workflows:
  deploy:
    jobs:
      - yarn/workflow-queue
      - yarn/update-cache:
          requires:
            - yarn/workflow-queue
      - deploy:
          requires:
            - yarn/update-cache
          branches:
            only:
              - master
